# Generated by Django 3.0.4 on 2020-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('id_no', models.CharField(blank=True, max_length=5, null=True)),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=3, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('testtype', models.CharField(blank=True, max_length=100, null=True)),
                ('testdate', models.CharField(blank=True, max_length=100, null=True)),
                ('papertype', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('is_test_added', models.BooleanField(default=False)),
                ('is_solution_added', models.BooleanField(default=False)),
                ('question_path', models.CharField(blank=True, max_length=250, null=True)),
                ('solution_path', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
