# Generated by Django 3.0.4 on 2020-03-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20200314_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='column',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
